In [3]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(suppress=True)

In [4]:
mu = 398600 #km^3 / s^2
#case 1
# r_0 = np.array([-6115.75, -6586.18, -58.65]) #km
# v_0 = np.array([4.42, -4.26,-1.08]) #km/s

#case 2
r_0 = np.array([6590, 0, 0]) #km
v_0 = np.array([0, 10.153, 1.247]) #km/s

In [5]:
r_0mag = la.norm(r_0)
r_0mag

6590.0

In [6]:
v_0mag = la.norm(v_0)
v_0mag 

10.229292155374193

In [7]:
#semi-major axis
a = 1 / ( (2/r_0mag) - ((v_0mag**2)/mu) )
a

24404.95258510698

In [8]:
#angular momentum
h = np.cross(r_0,v_0)
h#la.norm(h)

array([    0.  , -8217.73, 66908.27])

In [9]:
#eccentricity
e = ( np.cross(v_0,h) / mu ) - r_0 / la.norm(r_0)
e

array([ 0.72997284,  0.        , -0.        ])

In [10]:
la.norm(e)

0.7299728414952336

In [11]:
K = np.array([0,0,1])
I = np.array([1,0,0])
#node
n = np.cross(K,h) / la.norm(h)
n

array([ 0.12190482,  0.        , -0.        ])

In [12]:
little_omega = np.arccos( np.dot(n,e) / (la.norm(e) * la.norm(n)) )
little_omega

0.0

In [13]:
big_omega = np.arccos(np.dot(n,I)/ la.norm(n))
big_omega

0.0

In [14]:
f = np.arccos( np.dot(r_0,e) / (la.norm(e) * la.norm(r_0)) )
f

0.0

In [15]:
np.dot(r_0,v_0)

0.0

In [16]:
T = 2 * np.pi * np.sqrt(la.norm(a* (1+la.norm(e)))**3 / mu)
T/(60*60)

23.981955935439892

In [17]:
a * (1 + la.norm(e)) / 6378

6.619615109785822

In [18]:
#orbital elements
#case 1
# a = 8000
# e = 0.125
# i = np.radians(10)
# big_omega = np.radians(45)
# lil_omega = np.radians(10)
# M = np.radians(170)

#case 2
r_p = 6611
e = 0.01
a = r_p / (1 - e)
i = np.radians(90)
big_omega = 0
lil_omega = 0
M = np.radians(355)

In [19]:
def getE(M):
    E_curr = M
    err = 1
    tol = 1e-10
    while (abs(err) > tol):
        err = M - E_curr + e * np.sin(E_curr)
        derrdE = -1 + e * np.cos(E_curr)
        E_next = E_curr - err / derrdE
        E_curr = E_next
    return E_curr

In [20]:
E = getE(M)
E #- 2 * np.pi

6.195038517721757

In [21]:
f = 2 * np.arctan2(np.tan(E/2) * np.sqrt(1 + e), np.sqrt(1-e))
f #+ np.pi * 2

-0.08903154498063698

In [22]:
h = np.sqrt(mu * a * (1-e**2))
h

51589.68933808382

In [23]:
theta = lil_omega + f
theta

-0.08903154498063698

In [24]:
r_mag = h**2 / (mu * ( 1 + e * np.cos(f) ) )
r_mag

6611.259258942783

In [25]:
r = r_mag * np.array([
    np.cos(theta) * np.cos(big_omega) - np.cos(i) * np.sin(big_omega) * np.sin(theta),
    np.cos(theta) * np.sin(big_omega) + np.cos(i) * np.cos(big_omega) * np.sin(theta),
    np.sin(i) * np.sin(theta)
])
r

array([6585.07410572,   -0.        , -587.83331916])

In [26]:
v = -(mu/h) * np.array([
    np.cos(big_omega) * (np.sin(theta) + e * np.sin(lil_omega)) + np.sin(big_omega) * (np.cos(theta) + e * np.cos(lil_omega)) * np.cos(i),
    np.sin(big_omega) * (np.sin(theta) + e * np.sin(lil_omega)) - np.cos(big_omega) * (np.cos(theta) + e * np.cos(lil_omega)) * np.cos(i),
    -(np.cos(theta) + e * np.cos(lil_omega)) * np.sin(i)
])
v

array([0.68698047, 0.        , 7.77301189])

In [33]:
#orbital elements
a = 26553
e = 0

In [37]:
T_og = 2.0 * np.pi * np.sqrt(a**3 / mu)
T_ph = T_og - 5.0 * 60.0
T_ph

42760.75243985843

In [46]:
a_ph = ( mu * ( T_ph / (2 * np.pi) )**2 )**(1/3)
print('correct', a_ph)

correct 26429.528270537467


In [39]:
T_ph * 3 / (60 * 60)

35.63396036654869

In [40]:
v_og = np.sqrt(mu/a)
v_og

3.87446595817284

In [44]:
r_a = a
r_p = 2 * a_ph - r_a
print('correct', r_p)

correct 26306.056541074933


In [42]:
e_ph = (r_a - r_p) / (r_a + r_p)
e_ph

0.004671734137615105

In [45]:
h = np.sqrt(mu * a_ph * (1 - e_ph**2))
print('correct', h)

correct 102638.10230785028


In [73]:
v_a_ph = np.sqrt(mu * ((2/r_a) - (1/a_ph)) )
v_a_ph

3.8668513580916106

In [74]:
(v_og - v_a_ph) * 2

0.01814913843639321