In [3]:
import numpy as np
from numpy import linalg as la
import control as ctl
from scipy import linalg
from scipy import signal as sig

In [4]:
A1 = np.array([[-9.8, -48.3, -18.9], [3.0, 14.8, 5.8], [-2.4, -11.9, -4.7]])
A2 = np.array([[0.3, -0.3], [0.3, -0.3]])
A3 = np.array([[-0.5, -0.5], [1.0, 1.0]])
A4 = np.array([[9.7, 17.0, 0.0], [-5.6, -9.8, 0.0], [13.3, 23.4, 0.0]])
A5 = np.array([[-43.0, -73.3, -151.5], [38.7, 65.5, 134.0], [-6.7, -11.2, -22.5]])
C1 = np.array([[-0.3, -0.9, 0.1]])
C2 = np.array([[0.1, -0.1]])
C3 = np.array([[0.0, -0.1]])
C4 = np.array([[-0.4, -0.7, 0.0]])
C5 = np.array([[2.1, 3.7, 7.9]])

In [9]:
W = ctl.ctrb(A1.T,C1.T)
la.matrix_rank(W)

3

In [40]:
A = np.array([[-0.10, -0.90, 0.80, -0.50], [0.60, 0.00, -0.70, 0.30], [0.90, 0.90, 0.60, 0.50], [0.90, -0.90, -0.20, 0.90]])
B = np.array([[0.20], [0.20], [0.70], [0.80]])
C = np.array([[0.30, -0.10, -0.60, -0.40]])
K = np.array([[-6.00, -14.50, -0.80, 10.60]])
L = np.array([[-251.30], [37.90], [-262.00], [160.30]])

In [41]:

# F = np.concatenate((np.concatenate((A, -B @ K), axis=1), np.concatenate((L @ C, A - B @ K - L @ C), axis = 1)), axis = 0)

F = np.concatenate((np.concatenate((A - B @ K, -B @ K), axis=1), np.concatenate((np.zeros(A.shape), A - L @ C), axis = 1)), axis = 0)

In [42]:
F

array([[   1.1 ,    2.  ,    0.96,   -2.62,    1.2 ,    2.9 ,    0.16,
          -2.12],
       [   1.8 ,    2.9 ,   -0.54,   -1.82,    1.2 ,    2.9 ,    0.16,
          -2.12],
       [   5.1 ,   11.05,    1.16,   -6.92,    4.2 ,   10.15,    0.56,
          -7.42],
       [   5.7 ,   10.7 ,    0.44,   -7.58,    4.8 ,   11.6 ,    0.64,
          -8.48],
       [   0.  ,    0.  ,    0.  ,    0.  ,   75.29,  -26.03, -149.98,
        -101.02],
       [   0.  ,    0.  ,    0.  ,    0.  ,  -10.77,    3.79,   22.04,
          15.46],
       [   0.  ,    0.  ,    0.  ,    0.  ,   79.5 ,  -25.3 , -156.6 ,
        -104.3 ],
       [   0.  ,    0.  ,    0.  ,    0.  ,  -47.19,   15.13,   95.98,
          65.02]])

In [43]:
# G = np.concatenate((-B / (C @ la.inv(A - B @ K) @ B), -B / (C @ la.inv(A - B @ K) @ B)))
G = np.concatenate((-B / (C @ la.inv(A - B @ K) @ B), np.zeros(B.shape)))

G

array([[0.30095272],
       [0.30095272],
       [1.05333453],
       [1.20381089],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]])

In [44]:
H = np.concatenate((C, np.zeros(C.shape)), axis=1)
H

array([[ 0.3, -0.1, -0.6, -0.4,  0. ,  0. ,  0. ,  0. ]])

In [48]:
A = np.array([[0.30, 0.60, 0.90], [0.90, -0.10, 0.10], [-0.10, -0.80, -0.30]])
B = np.array([[0.70], [0.30], [0.00]])
C = np.array([[0.00, 0.70, 0.90]])
K = np.array([[1.50, 1.60, 1.10]])
L = np.array([[-11.70], [-21.30], [21.60]])
x0 = np.array([0.50, 0.60, -0.40])
xhat0 = np.array([0.40, -0.30, -0.10])
t0 = 0.10
t1 = 0.60

In [54]:
F = np.concatenate((np.concatenate((A, -B @ K), axis=1), np.concatenate((L @ C, A - B @ K - L @ C), axis = 1)), axis = 0)

In [55]:
e0 = np.concatenate((x0,xhat0), axis = 0)
e = linalg.expm(F * (t1 - t0)) @ e0
print(e[0:3], e[3:])

[ 0.71150834  0.8726681  -0.64820137] [ 0.34655784 -0.55891051  0.58794283]


In [2]:
A = np.array([[0.60, 0.60, -0.90, -0.80], [0.40, 0.00, 0.70, 0.40], [-0.20, 0.80, -0.60, 0.10], [-0.10, -0.80, -0.80, 0.80]])
B = np.array([[0.50], [-0.60], [0.80], [-0.70]])
C = np.array([[-0.10, 0.30, 0.50, -0.80]])
K = np.array([[59.10, 57.10, 1.90, -16.60]])
L = np.array([[1259.60], [107.50], [-376.00], [-364.80]])
x0 = np.array([0.40, 0.80, 0.50, 0.50])
xhat0 = np.array([0.00, 1.80, 0.30, 1.50])
t0 = 0.20
t1 = 0.60

In [3]:
F = np.concatenate((np.concatenate((A - B @ K, -B @ K), axis=1), np.concatenate((np.zeros(A.shape), A - L @ C), axis = 1)), axis = 0)
print(F)

[[-2.89500e+01 -2.79500e+01 -1.85000e+00  7.50000e+00 -2.95500e+01
  -2.85500e+01 -9.50000e-01  8.30000e+00]
 [ 3.58600e+01  3.42600e+01  1.84000e+00 -9.56000e+00  3.54600e+01
   3.42600e+01  1.14000e+00 -9.96000e+00]
 [-4.74800e+01 -4.48800e+01 -2.12000e+00  1.33800e+01 -4.72800e+01
  -4.56800e+01 -1.52000e+00  1.32800e+01]
 [ 4.12700e+01  3.91700e+01  5.30000e-01 -1.08200e+01  4.13700e+01
   3.99700e+01  1.33000e+00 -1.16200e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.26560e+02
  -3.77280e+02 -6.30700e+02  1.00688e+03]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.11500e+01
  -3.22500e+01 -5.30500e+01  8.64000e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00 -3.78000e+01
   1.13600e+02  1.87400e+02 -3.00700e+02]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00 -3.65800e+01
   1.08640e+02  1.81600e+02 -2.91040e+02]]


In [45]:
e0 = np.concatenate((x0, xhat0 - x0))

In [46]:
ef = linalg.expm(F * (t1 - t0)) @ e0
ef

array([ 30.06008613, -55.20300072, 104.51400238, -13.10704875,
       -22.06575042,  -0.23061851,   9.12448679,   8.08913676])

In [47]:
xhat = ef[0:4] + ef[4:]
xhat

array([  7.99433571, -55.43361922, 113.63848917,  -5.017912  ])

In [114]:
A = np.array([[-0.8, -0.6, -0.9, 0.4], [-0.7, 0.7, -0.2, -0.8], [-0.6, 0.2, 0.7, 0.0], [0.2, -0.1, 0.5, -0.1]])
B = np.array([[-0.6], [0.2], [-0.1], [-0.3]])
C = np.array([[0.7, -0.7, 0.2, -0.1]])
K1 = np.array([[-1279.9, -2038.8, 6823.6, -1164.2]])
K2 = np.array([[-320.6, -633.5, 1977.0, -497.7]])
K3 = np.array([[-213.9, -818.9, 2080.7, -829.4]])
K4 = np.array([[-2989.5, -9517.6, 23684.1, -8345.9]])
K5 = np.array([[-834.5, -917.9, 3833.4, -313.7]])
L1 = np.array([[-3596.2], [-1510.8], [8443.1], [2005.2]])
L2 = np.array([[-3039.7], [-1395.3], [6419.2], [1116.6]])
L3 = np.array([[-3258.1], [-1556.4], [6298.3], [635.4]])
L4 = np.array([[-4808.3], [-2218.3], [9953.5], [1554.4]])
L5 = np.array([[-7082.7], [-3284.7], [14576.2], [2248.3]])

In [125]:
la.eig(A - B @ K4)[0]

array([-4.2780214+9.08175716j, -4.2780214-9.08175716j,
       -8.2419786+5.98686606j, -8.2419786-5.98686606j])

In [126]:
la.eig(A - L4 @ C)[0]

array([-5.09116724+8.45616183j, -5.09116724-8.45616183j,
       -7.8873809 +0.j        , -3.69028461+0.j        ])

In [57]:
A = np.array([[-0.60, -0.50], [-0.50, -0.60]])
B = np.array([[-0.70], [0.30]])
C = np.array([[0.40, 0.00]])
pObsv = np.array([[-4.00-2.00j, -4.00+2.00j]])
pCont = np.array([[-1.00-1.00j, -1.00+1.00j]])

In [58]:
L = ctl.acker(A.T, C.T, pObsv[0]).T
K = ctl.acker(A, B, pCont[0])

In [59]:
K

array([[0.715, 4.335]])

In [60]:
L

array([[ 17.  ],
       [-79.05]])

In [61]:
-1 / (C @ la.inv(A - B @ K) @ B)

array([[-8.77192982]])

In [158]:
np.concatenate((pObsv, pCont), axis=1)

array([[-2, -4, -1, -1]])

In [14]:
A = np.array([[-0.10, -0.40, 0.70, 0.30], [-0.50, 0.40, 0.40, -0.20], [0.10, 0.50, 0.70, -0.70], [0.90, 0.80, 0.80, 0.80]])
B = np.array([[-0.70], [0.80], [-0.80], [0.30]])
C = np.array([[-0.60, -0.10, 0.60, 0.90]])
K = np.array([[-20.60, 16.40, 10.00, -36.90]])
L = np.array([[-47.00], [66.70], [22.40], [-26.90]])
t0 = 1.00
h = 0.03
xhat0 = np.array([[-0.60], [1.00], [0.50], [0.80]])
r0 = -0.30
y0 = np.array([[0.20]])

In [15]:
kref = -1 / (C @ la.inv(A - B @ K) @ B)
u0 = -K @ xhat0 + r0 * kref
u0

array([[-4.51971331]])

In [13]:
xhat = xhat0
xhat += h * (A @ xhat + B @ u0 - L @ (C @ xhat - y0))
xhat

array([[ 1.02521398],
       [-1.24735312],
       [-0.11038688],
       [ 1.66988258]])