In [5]:
import numpy as np
from numpy import linalg as la
import sympy as sy
from scipy import signal

In [14]:
A = np.array([[-0.80, -0.80, 0.20], [-0.50, -0.60, -0.60], [-0.50, 0.70, 0.90]])
B = np.array([[0.00], [0.10], [-0.80]])
C = np.array([[0.00, 0.00, -0.30]])
D = np.array([[0]])
p = np.array([[1, 5]])

In [10]:
signal.place_poles(A, B, p[0]).gain_matrix.T

array([[-862.04556502],
       [-520.01021581],
       [ -80.06377698]])

In [11]:
Am = sy.Matrix(A)
Am.charpoly()

PurePoly(1.0*lambda**3 + 0.5*lambda**2 - 0.66*lambda + 0.634, lambda, domain='RR')

In [15]:
x = sy.S('x')
print(sy.poly((x - p[0][0]) * (x - p[0][1]) 
              # * (x - p[0][2])
              # * (x - p[0][3])
             ))

Poly(x**2 - 6*x + 5, x, domain='ZZ')


In [118]:
W = np.concatenate((B, A @ B, A @ A @ B, A @ A @ A @ B), axis = 1)
W

array([[ 0.8   , -0.53  ,  0.678 , -1.0093],
       [-0.4   , -0.53  ,  0.424 , -0.3575],
       [ 0.3   , -0.12  , -0.069 , -0.3588],
       [ 0.7   ,  0.01  ,  0.445 , -0.3767]])

In [119]:
ACCF = np.array([
    [-0.2,1.18,-0.292,-0.2043],
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0]
])
BCCF = np.array([
    [1],
    [0],
    [0],
    [0]
])
WCCF = np.concatenate((BCCF, ACCF @ BCCF, ACCF @ ACCF @ BCCF, ACCF @ ACCF @ ACCF @BCCF), axis=1)
WCCF

array([[ 1.   , -0.2  ,  1.22 , -0.772],
       [ 0.   ,  1.   , -0.2  ,  1.22 ],
       [ 0.   ,  0.   ,  1.   , -0.2  ],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [120]:
L = np.array([22.3 - 0.2, 186.9898  + 1.18, 690.787696  - 0.292, 902.4028416 - 0.2043])
L

array([ 22.1      , 188.1698   , 690.495696 , 902.1985416])

In [121]:
L @ WCCF @ la.inv(W)

array([  7249.68272527,  -5157.18046857, -11302.85495303,  -6356.65983106])

In [122]:
p = np.array([[5.0-1.0j, 5.0+1.0j]])
x = sy.S('x')
print(sy.poly((x - p[0][0]) * (x - p[0][1]) 
             ))

Poly(1.0*x**2 - 10.0*x + 26.0, x, domain='CC')


In [16]:
A = np.array([[ 3, -2, -3], [ 0, -3,  1], [-3, -1, -2]])
Am = sy.Matrix(A)
Am.charpoly()

PurePoly(lambda**3 + 2*lambda**2 - 17*lambda - 54, lambda, domain='ZZ')

In [21]:
A = np.array([[-0.8, -1.0], [-0.2, 0.3]])
B = np.array([[-0.1], [-0.7]])

In [22]:
Am = sy.Matrix(A)
Am.charpoly()

PurePoly(1.0*lambda**2 + 0.5*lambda - 0.44, lambda, domain='RR')

In [126]:
ACCF = np.array([
    [0.8,0.52,-0.392],
    [1,0,0],
    [0,1,0]
])
BCCF = np.array([
    [1],
    [0],
    [0]
])

In [25]:
A = np.array([[0.9, 0.1], [-1.0, -0.9]])
B = np.array([[0.2], [-0.4]])
F = np.array([[1.9, 2.9], [-1.0, -1.9]])
G = np.array([[-0.6], [0.4]])

In [26]:
W1 = np.concatenate((B, A @ B), axis = 1)
W2 = np.concatenate((G, F @ G), axis = 1)

In [27]:
W1 @ la.inv(W2)

array([[-1.00000000e+00, -1.00000000e+00],
       [ 1.78443119e-16, -1.00000000e+00]])

In [130]:
A = np.array([[3.0, 5.0, 3.0, 3.0], [1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0]])
B = np.array([[1.0], [0.0], [0.0], [0.0]])
r = np.array([[13.0, 37.0, 75.0, 50.0]])

In [131]:
Am = sy.Matrix(A)
Am.charpoly()

PurePoly(1.0*lambda**4 - 3.0*lambda**3 - 5.0*lambda**2 - 3.0*lambda - 3.0, lambda, domain='RR')

In [28]:
A = np.array([[0.3, 0.4, 0.9, 0.6], [0.1, -0.4, 0.4, -0.3], [1.0, 0.1, 0.5, -0.6], [-0.6, -0.2, 0.3, 0.3]])
B = np.array([[0.4], [0.2], [0.5], [-1.0]])
F = np.array([[2.5, -24.3, 6.5, 0.6], [-5.4, 35.0, -11.1, -0.3], [-16.2, 111.9, -34.7, -1.2], [-41.8, 266.1, -85.0, -2.1]])
G = np.array([[-1.5], [2.2], [6.9], [15.7]])
V = np.array([[ 1,  4, -1,  0], [-2,  5, -2,  0], [-2,  2, -1,  0], [-1, -2, -2,  1]])
L = np.array([[ 1, -5,  1, -5]])

In [29]:
# W1 = np.concatenate((B, A @ B), axis = 1)
# W2 = np.concatenate((G, F @ G), axis = 1)
# V = W1 @ la.inv(W2)
L @ la.inv(V)

array([[ -80.,  127., -165.,   -5.]])

In [65]:
A = np.array([[0.8, 1.0], [-0.9, 0.7]])
B = np.array([[0.1], [-0.2]])
p = np.array([[-5.0+4.0j, -5.0-4.0j]])

In [66]:
Am = sy.Matrix(A)
print(Am.charpoly())
x = sy.S('x')
print(sy.poly((x - p[0][0]) * (x - p[0][1]) 
              # * (x - p[0][2])
              # * (x - p[0][3])
              # * (x - p[0][4])
             ))

PurePoly(1.0*lambda**2 - 1.5*lambda + 1.46, lambda, domain='RR')
Poly(1.0*x**2 + 10.0*x + 41.0, x, domain='CC')


In [67]:
# W = np.concatenate((B, A @ B, A @ A @ B, A @ A @ A @ B, A @ A @ A @ A @ B), axis = 1)
# ACCF = np.array([
#     [-0.4,-0.28, 0.031, 2.9868, 1.9872],
#     [1,0,0,0,0],
#     [0,1,0,0,0],
#     [0,0,1,0,0],
#     [0,0,0,1,0]
# ])
# BCCF = np.array([
#     [1],
#     [0],
#     [0],
#     [0],
#     [0]
# ])
# WCCF = np.concatenate((BCCF, ACCF @ BCCF, ACCF @ ACCF @ BCCF, ACCF @ ACCF @ ACCF @BCCF, ACCF @ ACCF @ ACCF @ ACCF @BCCF), axis=1)
# BCCF
ACCF = np.array([
    [1.5,-1.46],
    [1,0]
])
BCCF = np.array([
    [1],
    [0]
])
W = np.concatenate((B, A @ B), axis = 1)
WCCF = np.concatenate((BCCF, ACCF @ BCCF), axis=1)

In [68]:
KCCF = np.array([10,41]) + ACCF[0]
KCCF

array([11.5 , 39.54])

In [69]:
V_inv = WCCF @ la.inv(W)
la.inv(V_inv)

array([[ 0.1 , -0.27],
       [-0.2 ,  0.07]])

In [70]:
KCCF @ V_inv

array([-185.38297872, -150.19148936])

In [71]:
signal.place_poles(A, B, p[0]).gain_matrix.T

array([[-185.38297872],
       [-150.19148936]])