In [1]:
import numpy as np
from numpy import linalg as la

In [6]:
A = np.array([[-0.4, 0.1, 0.9, -0.4], [0.4, 0.9, -0.9, 0.4], [-0.9, 0.6, -0.7, 0.9], [-0.7, 0.9, -0.3, -0.4]])
B = np.array([[0.6], [0.7], [0.8], [-0.1]])
C = np.array([[-0.4, -0.5, -0.9, -0.6]])
D = np.array([[0.0]])
K = np.array([[9.5, 47.1, -34.8, 0.9]])

In [7]:
-1 / (C @ la.inv(A - B @ K) @ B)

array([[-6.29718819]])

In [10]:
A = np.array([[ 0,  2], [-2,  0]])
B = np.array([[ 0], [-6]])
C = np.array([[ 0, -9]])
D = np.array([[0]])
K = np.array([[-3.2, -2.3]])

In [12]:
-1 / (C @ la.inv(A - B @ K) @ B)

C:\Users\phlee\AppData\Local\Temp\ipykernel_42752\2332959363.py:1: RuntimeWarning: divide by zero encountered in divide
  -1 / (C @ la.inv(A - B @ K) @ B)


array([[-inf]])

In [13]:
A = np.array([[0.60000000, -0.50000000, 0.40000000, -0.30000000], [-0.70000000, 0.80000000, 0.50000000, 0.80000000], [0.60000000, 0.00000000, -0.70000000, -0.70000000], [0.80000000, 0.30000000, -0.10000000, 0.70000000]])
B = np.array([[-0.50000000], [-0.70000000], [0.80000000], [-0.60000000]])
C = np.array([[0.60000000, 0.50000000, -0.40000000, -0.80000000]])
D = np.array([[0.00000000]])
K = np.array([[8.10000000, -12.50000000, -2.10000000, -5.10000000]])
kRef = np.array([[7.00000000]])

In [14]:
(-C @ la.inv(A - B @ K) @ B * kRef - 1)

array([[0.76783334]])

In [15]:
A = np.array([[-0.30000000, 0.50000000], [-0.20000000, 0.30000000]])
B = np.array([[0.90000000], [-0.10000000]])
C = np.array([[-0.70000000, -0.70000000]])
D = np.array([[0.00000000]])
K = np.array([[4.10000000, -10.40000000]])
kRef = np.array([[2.37735849]])

In [16]:
E = A - B @ K
F = B * kRef
E,F

(array([[-3.99,  9.86],
        [ 0.21, -0.74]]),
 array([[ 2.13962264],
        [-0.23773585]]))

In [1]:
G = 

NameError: name 'np' is not defined